# Generated by Django 4.2.7 on 2023-11-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(choices=[('Ol', 'Online Learning'), ('Odl', 'Open and Distance Learning'), ('Regular', 'Regular Classroom')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=8)),
            ],
        ),
    ]
