# Generated by Django 4.2.5 on 2023-11-02 08:55

from django.db import migrations, models
import django.db.models.deletion
import exam_sch.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="roles",
            fields=[
                ("role_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "role_name",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Co-Ordinator", "Co-ordinator"),
                            ("Student", "Student"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                (
                    "password",
                    models.TextField(default=exam_sch.models.generate_random_password),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="user_table",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=255)),
                ("user_email", models.EmailField(max_length=254, unique=True)),
                ("user_password", models.TextField()),
                (
                    "user_gender",
                    models.CharField(
                        choices=[
                            ("Male", "male"),
                            ("Female", "female"),
                            ("Other", "other"),
                        ],
                        max_length=12,
                    ),
                ),
                ("department", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        max_length=12,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_with_rolename",
                        to="exam_sch.roles",
                    ),
                ),
                (
                    "user_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_with_role",
                        to="exam_sch.roles",
                    ),
                ),
                (
                    "user_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_with_role_name",
                        to="exam_sch.roles",
                    ),
                ),
            ],
        ),
    ]
