# Generated by Django 4.2.5 on 2023-11-03 07:33

from django.db import migrations, models
import exam_sch.models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_sch", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roles",
            name="password",
        ),
        migrations.AlterField(
            model_name="roles",
            name="role_name",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Co-Ordinator", "Co-ordinator"),
                    ("Student", "Student"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="roles",
            name="updated_by",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="user_table",
            name="user_password",
            field=models.TextField(default=exam_sch.models.generate_random_password),
        ),
    ]
