# Generated by Django 4.2.5 on 2023-11-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_sch", "0003_remove_user_table_user_role_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roles",
            name="updated_by",
        ),
        migrations.AlterField(
            model_name="user_table",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Co-Ordinator", "Co-ordinator"),
                    ("Student", "Student"),
                ],
                max_length=12,
            ),
        ),
    ]
