# Generated by Django 4.2.5 on 2023-11-04 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exam_sch", "0004_remove_roles_updated_by_alter_user_table_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_table",
            name="user_type",
        ),
        migrations.AddField(
            model_name="user_table",
            name="user_role",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="exam_sch.roles",
            ),
        ),
        migrations.AlterField(
            model_name="user_table",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users_created",
                to="exam_sch.roles",
            ),
        ),
    ]
