# Generated by Django 4.2.5 on 2023-11-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_sch", "0005_remove_user_table_user_type_user_table_user_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roles",
            name="role_name",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Co-Ordinator", "Co-ordinator"),
                    ("Student", "Student"),
                ],
                max_length=12,
                unique=True,
            ),
        ),
    ]
