# Generated by Django 4.2.5 on 2023-11-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exam_sch", "0006_alter_roles_role_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_table",
            old_name="user_role",
            new_name="user_role_id",
        ),
    ]
