# Generated by Django 4.2.5 on 2023-11-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_sch", "0009_dept_session_alter_user_table_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programme_Level",
            fields=[
                ("prog_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "prog_name",
                    models.CharField(
                        choices=[("UG", "UG"), ("PG", "PG")], max_length=10
                    ),
                ),
                (
                    "prog_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="session",
            name="dept_name",
        ),
    ]
