# Generated by Django 4.2.5 on 2023-11-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_sch", "0010_programme_level_remove_session_dept_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dept",
            name="dept_name",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("odl", "Online-Distance Learning"),
                    ("regular", "Regular"),
                ],
                max_length=10,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="programme_level",
            name="prog_name",
            field=models.CharField(
                choices=[("UG", "UG"), ("PG", "PG")], max_length=10, unique=True
            ),
        ),
    ]
