# Generated by Django 4.2.5 on 2023-11-06 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exam_sch", "0011_alter_dept_dept_name_alter_programme_level_prog_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="gender",
            fields=[
                ("gender_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "gender_name",
                    models.CharField(
                        choices=[
                            ("Male", "male"),
                            ("Female", "female"),
                            ("Other", "other"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "gender_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        max_length=12,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="user_table",
            name="user_gender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="exam_sch.gender",
            ),
        ),
    ]
