# Generated by Django 4.2.5 on 2023-11-06 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exam_sch", "0012_gender_alter_user_table_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_table",
            name="user_gender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="exam_sch.gender",
            ),
        ),
    ]
