# Generated by Django 4.2.5 on 2023-11-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_sch", "0015_alter_user_table_user_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program_type",
            fields=[
                (
                    "program_type_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("program_type_name", models.CharField(max_length=255)),
                ("program_type_code", models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
