# Generated by Django 4.2.5 on 2023-11-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_sch", "0017_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                ("semester_id", models.AutoField(primary_key=True, serialize=False)),
                ("semester_name", models.CharField(max_length=255, unique=True)),
                ("semester_code", models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
