# Generated by Django 4.2.5 on 2023-11-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam_sch", "0019_remove_semester_semester_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                ("slot_id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("date", models.DateField()),
                (
                    "slot_created",
                    models.CharField(editable=False, max_length=11, unique=True),
                ),
            ],
        ),
    ]
