# Generated by Django 4.2.7 on 2023-11-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sch', '0020_slot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program_type',
            new_name='Program',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='program_type_code',
            new_name='program_code',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='program_type_id',
            new_name='program_id',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='program_type_name',
            new_name='program_name',
        ),
        migrations.RenameField(
            model_name='programme_level',
            old_name='prog_id',
            new_name='prog_level_id',
        ),
        migrations.RenameField(
            model_name='programme_level',
            old_name='prog_name',
            new_name='prog_level_name',
        ),
    ]
