# Generated by Django 4.2.7 on 2023-11-07 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sch', '0023_rename_prog_level_id_program_prog_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='program',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_sch.program'),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_sch.semester'),
        ),
    ]
