# Generated by Django 4.2.7 on 2023-11-16 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sch', '0024_subject_program_subject_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='id',
        ),
        migrations.AddField(
            model_name='slot',
            name='subject',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_sch.subject'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_code',
            field=models.CharField(editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_uid', models.CharField(editable=False, max_length=11, unique=True)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_sch.gender')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_sch.program')),
                ('program_level', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_sch.programme_level')),
                ('session', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_sch.session')),
                ('subjects', models.ManyToManyField(to='exam_sch.subject')),
            ],
        ),
    ]
