# Generated by Django 4.2.7 on 2023-11-16 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sch', '0025_remove_session_id_slot_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='program',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exam_sch.program'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exam_sch.semester'),
        ),
    ]
