# Generated by Django 4.2.7 on 2023-11-17 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sch', '0027_alter_subject_program_alter_subject_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='semester',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_sch.semester'),
        ),
    ]
