# Generated by Django 4.2.7 on 2023-11-22 07:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0031_rename_user_id_user_table_userid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_table",
            old_name="userid",
            new_name="id",
        ),
    ]
