# Generated by Django 4.2.7 on 2023-11-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0032_rename_userid_user_table_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentenrollment",
            name="student_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="student_uid",
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
