# Generated by Django 4.2.7 on 2023-11-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0033_alter_studentenrollment_student_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentenrollment",
            name="student_uid",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
