# Generated by Django 4.2.7 on 2023-11-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0034_alter_studentenrollment_student_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="subject_code",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="subject",
            name="subject_name",
            field=models.CharField(max_length=255),
        ),
    ]
