# Generated by Django 4.2.7 on 2023-11-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0035_alter_subject_subject_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_table",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
