# Generated by Django 4.2.7 on 2023-11-29 05:31

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0036_user_table_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentenrollment",
            name="user_mobile",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Enter your mobile number",
                max_length=128,
                null=True,
                region=None,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="user_table",
            name="user_mobile",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Enter your mobile number",
                max_length=128,
                null=True,
                region=None,
                unique=True,
            ),
        ),
    ]
