# Generated by Django 4.2.7 on 2023-11-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0037_studentenrollment_user_mobile_user_table_user_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_table",
            name="last_login_ip",
            field=models.GenericIPAddressField(
                blank=True, help_text="Last login IP address", null=True
            ),
        ),
    ]
