# Generated by Django 4.2.7 on 2023-11-29 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0038_user_table_last_login_ip"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialization",
            fields=[
                ("spec_id", models.AutoField(primary_key=True, serialize=False)),
                ("spec_name", models.CharField(max_length=255)),
                ("spec_code", models.CharField(max_length=10)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exam_sch.program",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exam_sch.semester",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="spec_id",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="exam_sch.specialization",
            ),
        ),
    ]
