# Generated by Django 4.2.7 on 2023-11-29 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0039_specialization_studentenrollment_spec_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentenrollment",
            old_name="spec_id",
            new_name="spec",
        ),
    ]
