# Generated by Django 4.2.7 on 2023-11-30 07:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0040_rename_spec_id_studentenrollment_spec"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentenrollment",
            name="student_mobile",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Enter your mobile number",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="student_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="student_uid",
            field=models.CharField(max_length=13),
        ),
        migrations.AlterUniqueTogether(
            name="studentenrollment",
            unique_together={("session", "student_uid")},
        ),
        migrations.RemoveField(
            model_name="studentenrollment",
            name="user_mobile",
        ),
    ]
