# Generated by Django 4.2.7 on 2023-11-30 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0041_studentenrollment_student_mobile_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentenrollment",
            old_name="subjects",
            new_name="subject",
        ),
    ]
