# Generated by Django 4.2.7 on 2023-12-04 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0042_rename_subjects_studentenrollment_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Electives",
            fields=[
                ("elec_id", models.AutoField(primary_key=True, serialize=False)),
                ("elec_category", models.CharField(max_length=255)),
                ("elec_code", models.CharField(max_length=10)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exam_sch.program",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exam_sch.semester",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="elec",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="exam_sch.electives",
            ),
        ),
    ]
