# Generated by Django 4.2.7 on 2023-12-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0044_specialization_spec_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="electives",
            name="elec_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
