# Generated by Django 4.2.7 on 2023-12-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0045_electives_elec_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentenrollment",
            name="elec",
        ),
        migrations.RemoveField(
            model_name="studentenrollment",
            name="spec",
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="elec",
            field=models.ManyToManyField(to="exam_sch.electives"),
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="spec",
            field=models.ManyToManyField(to="exam_sch.specialization"),
        ),
    ]
