# Generated by Django 4.2.7 on 2023-12-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0046_remove_studentenrollment_elec_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentenrollment",
            name="elec",
            field=models.ManyToManyField(null=True, to="exam_sch.electives"),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="spec",
            field=models.ManyToManyField(null=True, to="exam_sch.specialization"),
        ),
    ]
