# Generated by Django 4.2.7 on 2023-12-12 06:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0047_alter_studentenrollment_elec_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentenrollment",
            name="subject",
        ),
    ]
