# Generated by Django 4.2.7 on 2023-12-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0050_alter_slot_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="slot_created",
            field=models.CharField(editable=False, max_length=11),
        ),
    ]
