# Generated by Django 4.2.7 on 2023-12-18 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0051_alter_slot_slot_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="slot",
            name="session",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="exam_sch.session",
            ),
        ),
    ]
