# Generated by Django 4.2.7 on 2023-12-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0052_slot_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slot",
            name="date",
        ),
        migrations.RemoveField(
            model_name="slot",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="slot",
            name="slot_created",
        ),
        migrations.RemoveField(
            model_name="slot",
            name="start_time",
        ),
        migrations.AddField(
            model_name="slot",
            name="slot_1",
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="slot",
            name="slot_2",
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
