# Generated by Django 4.2.7 on 2023-12-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0053_remove_slot_date_remove_slot_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="slot_1",
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name="slot",
            name="slot_2",
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
