# Generated by Django 4.2.7 on 2023-12-19 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0054_alter_slot_slot_1_alter_slot_slot_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="session",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="exam_sch.session",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="slot_1",
            field=models.CharField(default=None, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name="slot",
            name="slot_2",
            field=models.CharField(default=None, editable=False, max_length=50),
        ),
    ]
