# Generated by Django 4.2.7 on 2023-12-19 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0056_alter_slot_session_alter_slot_slot_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="exam_sch.session"
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="slot_1",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="slot",
            name="slot_2",
            field=models.CharField(max_length=50),
        ),
    ]
