# Generated by Django 4.2.7 on 2023-12-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0057_alter_slot_session_alter_slot_slot_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slot",
            name="slot_1",
        ),
        migrations.RemoveField(
            model_name="slot",
            name="slot_2",
        ),
        migrations.AddField(
            model_name="slot",
            name="slot_list",
            field=models.TextField(blank=True, null=True),
        ),
    ]
