# Generated by Django 4.2.7 on 2023-12-19 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0058_remove_slot_slot_1_remove_slot_slot_2_slot_slot_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="exam_sch.session",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="exam_sch.subject",
            ),
        ),
    ]
