# Generated by Django 4.2.7 on 2023-12-20 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0066_alter_slot_session_alter_slot_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="session",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="exam_sch.session",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="slot",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="exam_sch.subject",
            ),
            preserve_default=False,
        ),
    ]
