# Generated by Django 4.2.7 on 2023-12-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0067_alter_slot_session_alter_slot_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="slot_list",
            field=models.TextField(),
        ),
    ]
