# Generated by Django 4.2.7 on 2023-12-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0069_specslot_elecslot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="slot_list",
            field=models.TextField(editable=False),
        ),
    ]
