# Generated by Django 4.2.7 on 2023-12-20 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0070_alter_slot_slot_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="subject",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="exam_sch.subject",
            ),
        ),
    ]
