# Generated by Django 4.2.7 on 2023-12-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0072_alter_slot_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="slot_id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
