# Generated by Django 4.2.7 on 2023-12-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam_sch", "0073_alter_slot_slot_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="slot_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="slot",
            name="slot_list",
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name="slot",
            unique_together={("session", "subject")},
        ),
    ]
