# Generated by Django 4.2.7 on 2023-11-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(choices=[('ol', 'Online'), ('odl', 'Online-Distance Learning'), ('regular', 'Regular')], max_length=10)),
                ('dept_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('year', models.PositiveIntegerField()),
                ('month', models.CharField(choices=[('Jan', 'January'), ('Jul', 'July')], max_length=3)),
                ('session_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
            ],
        ),
    ]
